### ISSUE TITLE
Images all online?

### ISSUE THREAD

**Issue by Alex-Keyes** [sotojuan/met#1]
Hey Juan,

are all the images of the artwork hosted on the met website or are there some that aren't on the met.  Is there any searching involved in getting the correct image of the artwork from the CSV file?

**Comment by sotojuan** [comment]
Hi Alex, sorry I never got any notification for this.

This little service interacts with the images that are hosted by the Met. If an image is not on their site (or is but it's not public domain), then it won't find it. The only useful information the CSV file has is the object id, which the Met API needs to return information about an image, including the full size link.

**Comment by Alex-Keyes** [comment]
Hi Juan,

Sounds cool! Any plans on what to use this API for?

**Comment by sotojuan** [comment]
I have some ideas but not sure since the Met's API is kind of weird and undocumented. I mostly wanted some Elixir practice!
